<?php

/**
 * Implements hook_help().
 */
function stanford_easy_wysiwyg_css_help($path, $arg) {
  switch ($path) {
    case 'admin/help#stanford_easy_wysiwyg_css':
      return '<p>' . t('Ask John.') . '</p>';
  }
}

/**
 * Implements hook_css_alter().
 */
function stanford_easy_wysiwyg_css_css_alter(&$css) {
  global $theme;
  $easy = variable_get("stanford_easy_wysiwyg_css", array());

  // Only add if we don't already have one.
  if (isset($easy[$theme])) {
    return;
  }

  // Allow theme to alter first.
  $func = $theme . "_css_alter";
  if (function_exists($func)) {
    $func($css);
  }

  $wysiwyg_css_data = drupal_add_css();
  $wysiwyg_css = array();

  // Remove print stuff.
  foreach ($wysiwyg_css_data as $path => $data) {
    if ($data['media'] == "print") {
      continue;
    }
    $wysiwyg_css[] = $path;
  }

  $easy[$theme] = $wysiwyg_css;
  variable_set("stanford_easy_wysiwyg_css", $easy);

}

/**
 * Implements hook_flush_caches().
 */
function stanford_easy_wysiwyg_css_flush_caches() {
  variable_del('stanford_easy_wysiwyg_css');
}

/**
 * [stanford_easy_wysiwyg_css_wysiwyg_editor_settings_alter description]
 * @param  [type] &$settings [description]
 * @param  [type] $context   [description]
 * @return [type]            [description]
 */
function stanford_easy_wysiwyg_css_wysiwyg_editor_settings_alter(&$settings, $context) {

  if ($context['profile']->settings['css_setting'] == "easy") {
    $sheets = stanford_easy_wysiwyg_css_get_sheets();
    foreach ($sheets as $k => $url) {
      $sheets[$k] = url($url);
    }
    $settings['contentsCss'] = $sheets;
  }

}

/**
 * [stanford_easy_wysiwyg_css_get_sheets description]
 * @return [type] [description]
 */
function stanford_easy_wysiwyg_css_get_sheets() {
  global $theme;
  global $theme_key;
  global $theme_path;
  $original_theme = $theme;
  $original_theme_key = $theme_key;
  $original_theme_path = $theme_path;
  $easy = variable_get("stanford_easy_wysiwyg_css", array());
  $theme_default = variable_get("theme_default");

  // Woot we have the stuff.
  if (isset($easy[$theme_default])) {
    return $easy[$theme_default];
  }

  $css = drupal_add_css();
  $original_css = $css;
  drupal_static_reset('drupal_add_css');

  // Remove theme layer stuff...
  foreach ($css as $path => $data) {
    if ($data['group'] == CSS_THEME) {
      unset($css[$path]);
    }
  }

  $themes = list_themes();
  $theme_info = $themes[$theme_default];
  $base_theme_info = !empty($themes[$theme_info->base_theme]) ? $themes[$theme_info->base_theme] : FALSE;

  // add defined stylesheets!
  foreach ($theme_info->stylesheets as $media => $values) {
    if ($media == "print") {
      continue;
    }
    foreach ($values as $local_path => $full_path) {
      drupal_add_css(drupal_get_path("theme", $theme_default) . "/" . $local_path);
    }
  }

  if ($base_theme_info) {
    // add defined stylesheets!
    foreach ($base_theme_info->stylesheets as $media => $values) {
      if ($media == "print") {
        continue;
      }
      foreach ($values as $local_path => $full_path) {
        drupal_add_css(drupal_get_path("theme", $theme_info->base_theme) . "/" . $local_path);
      }
    }
  }

  $add_css = drupal_add_css();

  // Allow theme to alter first.
  @include_once drupal_get_path("theme", $theme_default) . "/template.php";
  $func = $theme_default . "_css_alter";
  if (function_exists($func)) {
    $theme = $theme_default;
    $theme_key = $theme_default;
    $theme_path = drupal_get_path("theme", $theme_default);
    $func($add_css);
    $theme = $original_theme;
    $theme_key = $original_theme_key;
    $theme_path = $original_theme_path;
  }

  $final_css = drupal_add_css();

  // Return to our normally scheduled program.
  drupal_static_reset('drupal_add_css');
  foreach ($original_css as $path => $options) {
    drupal_add_css($path, $options);
  }

  $combined = $css + $final_css;
  return array_keys($combined);
}

/**
 * [stanford_easy_wysiwyg_form_css_wysiwyg_profile_form_alter description]
 * @param  [type] $form       [description]
 * @param  [type] $form_state [description]
 * @return [type]             [description]
 */
function stanford_easy_wysiwyg_css_form_wysiwyg_profile_form_alter(&$form, &$form_state) {
  $form['css']['css_setting']['#options']['easy'] = t("Default theme aggregated css");
}
